export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const GET_TRENDING_DEALS = 'GET_TRENDING_DEALS';
export const DEALS_LOADING = 'DEALS_LOADING';
export const DEAL_NOT_FOUND = 'DEAL_NOT_FOUND';
export const GET_DEAL_DETAIL = 'GET_DEAL_DETAIL';
export const DEALS_OF_THE_DAY = 'DEALS_OF_THE_DAY';
export const GET_FEATURED_DEALS = 'GET_FEATURED_DEALS';
export const GET_ALL_DEALS = 'GET_ALL_DEALS';
export const DEAL_VIEWED = 'DEAL_VIEWED';
export const MIXED_DEALS='MIXED_DEALS'

export const GET_FEATURED_STORES = 'GET_FEATURED_STORES';
export const STORES_LOADING = 'STORES_LOADING';
export const GET_STORE_DETAIL = 'GET_STORE_DETAIL';
export const GET_FOLLOWED_STORES = 'GET_FOLLOWED_STORES';
export const FOLLOW_STORE = 'FOLLOW_STORE';
export const EDIT_STORE = 'EDIT_STORE';

export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const GET_FOLLOWED_CATEGORIES = 'GET_FOLLOWED_CATEGORIES';
export const FOLLOW_CATEGORY = 'FOLLOW_CATEGORY';
export const OFFERS_BY_CATEGORY = 'OFFERS_BY_CATEGORY';
export const OFFERS_BY_SUBCATEGORY = 'OFFERS_BY_SUBCATEGORY';

export const GET_ALL_COUPONS = 'GET_ALL_COUPONS';
export const COUPONS_LOADING = 'COUPONS_LOADING';
export const GET_TRENDING_COUPONS = 'GET_TRENDING_COUPONS';
export const GET_FEATURED_COUPONS = 'GET_FEATURED_COUPONS';
export const GET_COUPON_DETAIL = 'GET_COUPON_DETAIL';
export const CLAIM_COUPON = 'CLAIM_COUPON';
export const VIEW_CLAIM_COUPON = 'VIEW_CLAIM_COUPON';
export const COUPON_VIEWED = 'COUPON_VIEWED';
export const GET_COUPON_CATEGORY = 'GET_COUPON_CATEGORY';
export const GET_OFFERS_HOME = 'GET_OFFERS_HOME';
export const GET_MIXED_COUPONS_HOME = 'GET_MIXED_COUPONS_HOME';

export const GET_FEATURED_PROMOTIONS = 'GET_FEATURED_PROMOTIONS';
export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';

export const GET_USER = 'GET_USER';
export const USER_LOADING = 'USER_LOADING';
export const USER_DETAILS = 'USER_DETAILS';
export const RELATED_OFFERS='RELATED_OFFERS'

//store dashboard
export const ADD_COUPONS = 'ADD_COUPONS';
export const DASHBOARD_LOADING = 'DASHBOARD_LOADING';
export const REGISTER_STORE = 'REGISTER_STORE';
export const GET_MY_STORES = 'GET_MY_STORES';
export const ADD_DEAL = 'ADD_DEAL';
export const CHANGE_STATUS_DEAL = 'CHANGE_STATUS_DEAL';
export const CHANGE_STATUS_COUPON = 'HANGE_STATUS_COUPON';
export const EDIT_DEAL = 'EDIT_DEAL';
export const EDIT_COUPON = 'EDIT_COUPON';

//unit purchase
export const GET_UNIT_PACKAGE = 'GET_UNIT_PACKAGE';
export const UNITS_LOADING = 'UNITS_LOADING';
export const PURCHASE_UNIT = 'PURCHASE_UNIT';
export const GET_STORE_UNIT = 'GET_STORE_UNIT';
export const GET_UNIT_TYPE = 'GET_UNIT_TYPE';
